[build]
  publish = "."
  functions = "netlify/functions"
  command = "cp index.html netlify/functions/index.html"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
  force = true